---
apiVersion: v1
kind: Namespace
metadata:
  name: default-789
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilency12
  namespace: default-789
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resilency12
  template:
    metadata:
      labels:
        app: resilency12
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: resilency12
          image: botsteam1.azurecr.io/resilency:latest
          imagePullPolicy: Always
          env:
             - name: AZURE_STORAGE_CONNECTION_STRING
               value: "Hello" 
             - name: CLIENT_ID
               value: "tet12323"
             - name: TENANT_ID
               value: "Mohamed123"
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: '256'
              memory: '11400G'
---
apiVersion: v1
kind: Service
metadata:
  name: resilency-service12
  namespace: default-789
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
    - targetPort: 443
      name: port443
      port: 443
      protocol: TCP
  selector:
    app: resilency12
