name: Linux Container Node Workflow

on: [push]

env:
  APP_NAME: 'apimbackend1'
  ACR_NAME: 'apimcr1'
  REPO_NAME: 'webapi'
jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./web-api

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'docker build and push'
      working-directory: ./web-api
      run: |
        docker build -f ./web-api/Dockerfile -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.REPO_NAME }}:${{ github.sha }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.REPO_NAME }}:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.APP_NAME}}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ env.ACR_NAME }}.azurecr.io/${{ env.REPO_NAME }}:${{ github.sha }}'
